name: "Build"

on:
  push:
    branches: [ "**" ]
    tags-ignore: [ "**" ]
  pull_request:
  workflow_dispatch:
    release:
      description: "Publish"
      type: boolean
      required: false
      default: false

jobs:
  build:
    name: "Build"
    uses: xpdustry/.github/.github/workflows/build-java.yaml@master
    with:
      java_version: 25
      release: ${{ github.event_name == 'workflow_dispatch' && inputs.release || false }}
      artifacts_path: build/release/*.jar
    secrets: "inherit"