name: "Build"

on:
  push:
    branches: [ "**" ]
    tags-ignore: [ "**" ]
  pull_request:
  workflow_dispatch:
    release:
      description: "Publish the project and increment version."
      type: boolean
      required: false
      default: false

jobs:
  build:
    uses: xpdustry/.github/.github/workflows/build-java.yaml@master
    with:
      java_version: 25
      release: ${{ github.event.inputs.release }}
      artifacts_path: build/release/*.jar
    secrets: "inherit"