name: Draft Release

on:
  workflow_dispatch:

jobs:
  action:
    name: "Action"
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:

      - name: "Checkout Repository"
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6
        with:
          fetch-tags: true
          fetch-depth: 0

      - name: "Checkout CI Scripts"
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6
        with:
          repository: xpdustry/.github
          path: .xpdustry-ci
          sparse-checkout: scripts

      - name: "Setup Java 25"
        uses: actions/setup-java@c1e323688fd81a25caa38c78aa6df2d33d3e20d9 # v4
        with:
          java-version: "25"
          distribution: "temurin"

      - name: "Setup Gradle"
        uses: gradle/actions/setup-gradle@748248ddd2a24f49513d8f472f81c3a07d4d50e1 # v4

      - name: "Get And Validate Version"
        id: version
        run: |
          version="$(./gradlew properties -q --no-daemon |\
            grep '^version:' | cut -d ':' -f 2 | xargs)"
          .xpdustry-ci/scripts/version-validate.sh "$version" "false"
          echo "version=${version%-SNAPSHOT}" >> "$GITHUB_OUTPUT"

      - name: "Generate Changelog"
        run: |
          .xpdustry-ci/scripts/changelog-generate.sh \
            "$GITHUB_REPOSITORY" \
            ".GENERATED_CHANGELOG.md"

      - name: "Create Draft Release"
        uses: softprops/action-gh-release@a06a81a03ee405af7f2048a818ed3f03bbf83c7b # v2
        with:
          tag_name: "v${{ steps.version.outputs.version }}"
          name: "v${{ steps.version.outputs.version }} release"
          draft: true
          body_path: ".GENERATED_CHANGELOG.md"
