name: "Publish Test Results"

on:
  workflow_run:
    workflows: [ "Build" ]
    types:
      - completed

jobs:
  action:
    name: "Action"
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event.workflow_run.conclusion == 'failure' }}
    runs-on: ubuntu-latest
    permissions:
      checks: write
      pull-requests: write # needed unless run with comment_mode: off
      contents: read # only needed for private repository
      issues: read # only needed for private repository
      actions: read # required by download step to access artifacts API
    steps:

      - name: "Download and Extract Test Results"
        uses: dawidd6/action-download-artifact@2536c51d3d126276eb39f74d6bc9c72ac6ef30d3 # v16
        with:
           run_id: ${{ github.event.workflow_run.id }}
           path: artifacts

      - name: "Publish Test Results"
        uses: EnricoMi/publish-unit-test-result-action@27d65e188ec43221b20d26de30f4892fad91df2f # v2
        with:
          commit: ${{ github.event.workflow_run.head_sha }}
          event_file: artifacts/event-file/event.json
          event_name: ${{ github.event.workflow_run.event }}
          files: "artifacts/**/*.xml"